kind: pipeline
type: exec
name: deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: deployment1
    commands:
      - git clone https://github.com/Eilison/test-drone.git
      - cd test-drone
      - git pull

branches: main
