kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: jar-deploy # 定义流水线名称
#node:
#  name: drone-runner-sczz

steps: # 定义流水线执行步骤，这些步骤将顺序执行

- name: test-ansible # 流水线名称
  image: plugins/ansible:3
  settings:
    become: true
    playbook: playbook.yml
    # galaxy: ansible/requirements.yml
    inventory: inventory
    syntax_check: true
    
- name: build-package # 流水线名称
  image: maven:3.8.6-jdk-8 # 定义创建容器的Docker镜像
  volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
    - name: maven-cache
      path: /root/.m2 # 将maven下载依赖的目录挂载出来，防止重复下载
    - name: maven-build
      path: /app/build # 将应用打包好的Jar和执行脚本挂载出来
  commands: # 定义在Docker容器中执行的shell命令
    - mvn clean package # 应用打包命令
    - cp target/demo-0.0.1-SNAPSHOT.jar /app/build/demo-0.0.1.jar

- name: deploy-start
  image: appleboy/drone-ssh # SSH工具镜像
  settings:
    host: 172.18.26.106 # 远程连接地址
    username: root # 远程连接账号
    password:
      from_secret: ssh_password # 从Secret中读取SSH密码
    port: 22 # 远程连接端口
    command_timeout: 5m # 远程执行命令超时时间
    script:
      - cd /root/drone/docker/maven/build # 进入宿主机构建目录
      - ll -a
  when:
    event:
      - promote

volumes: # 定义流水线挂载目录，用于共享数据
- name: maven-build
  host:
    path: /root/drone/docker/maven/build # 从宿主机中挂载的目录
- name: maven-cache
  host:
    path: /root/drone/docker/maven/cache
