---
# This playbook prints a simple debug message
- name: Echo
  hosts: 112.74.168.120
  remote_user: root
  # connection: local
  become: true

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: move jar
    copy: src=/app/build/demo-0.0.1.jar dest=/www/demo-0.0.1.jar
  - name: get pid of process
    tags:
     - test
    shell: "ll /www/demo*"
    register: jarname
  - name: Print debug message
    debug:
      msg: "{{jarname}}"
