---
# This playbook prints a simple debug message
- name: Echo
  hosts: 112.74.168.120
  remote_user: root
  # connection: local
  become: true

  tasks:
  - name: start deploy
    debug:
      msg: start deploy!
  - name: move jar
    copy: src=/app/build/{{ filname }}-0.0.1.jar dest=/www/{{ filname }}-0.0.1.jar backup=yes
  - name: get pid of process
    tags:
     - test
    shell: "ls -l /www/demo*"
    register: jarpath
  - name: Print debug message
    debug:
      msg: "{{jarpath}}"
  - name: finish deploy
    debug:
      msg: finish deploy!
